name: inf492
channels:
  - pytorch
  - conda-forge
dependencies:
  - pytorch
  - pytorch-cuda
  - pytorch-lightning
  - torchaudio
  - torchvision
  - jupyter
  - jupyterlab-git
  - ipykernel
  - matplotlib
  - numpy
  - opencv
  - pillow
  - scikit-image
  - scikit-learn
  - tensorboard
  - tqdm

